const CONFIG = {

    OPENWEATHER_API_KEY: "YOUR_OPENWEATHER_API_KEY",

    OPENROUTESERVICE_API_KEY: "YOUR_OPENROUTESERVICE_API_KEY",

    GEOAPIFY_API_KEY: "YOUR_GEOAPIFY_API_KEY",

    GEMINI_API_KEY: "YOUR_GEMINI_API_KEY"

};
